name: Windows Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v2
      

      - uses: msys2/setup-msys2@v2
        with:
          install: mingw-w64-x86_64-toolchain
          msystem: mingw64
          release: false

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.2.0'
          host: "windows"
          target: "desktop"
          arch: "win64_msvc2019_64"
          dir: "${{github.workspace}}/qt/"
          install-deps: "true"
          
      - uses: lukka/get-cmake@latest 
      - name: Configure CMake
        env:
          CMAKE_PREFIX_PATH: ${{env.Qt6_Dir}}
        run: cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "CodeBlocks - MinGW Makefiles" -B '${{github.workspace}}'/build
      - name: Build
        run: cmake --build '${{github.workspace}}'/build --target RePr
